[build]
  publish = "build/web"
  command = "echo 'Skipping build, using pre-built Flutter web'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200